name: 'Wait For TiDBCloud Branch'
description: 'Wait for TiDBCloud branch to be ready. Only used on pull request'
author: 'TiDBCloud ecosystem team'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: 'The GitHub token to use for making API requests.'
    required: true
  timeoutSeconds:
    description: 'The number of seconds to wait for the branch ready.'
    default: '300'
  intervalSeconds:
    description: 'The number of seconds to wait before each check.'
    default: '10'
  ref:
    description: 'The Git ref of the commit you want to poll for a passing check.'
outputs:
  message:
    description: 'The branch message.'
runs:
  using: 'node16'
  main: 'dist/index.js'
